### ISSUE TITLE
pattern.sub

### ISSUE THREAD

**Issue by Ulrar** [tylerhoadley/letsencrypt-automation#1]
Hi,

Looks good, could we maybe get the pattern.sub ? Don't really know what to do with all this when the most important file is missing :)

**Comment by tylerhoadley** [comment]
I've uploaded the pattern.template file, this is used to create the pattern.sub file that gets scp to the pfsense server and manipulates the pfsense config

**Comment by tylerhoadley** [comment]
you can also take a look at this thread

https://forum.pfsense.org/index.php?topic=107161.msg651063#msg651063
